CREATE TABLE `current_state` (
	`id` int(5) NOT NULL AUTO_INCREMENT,
	`name` varchar(50) DEFAULT NULL,
	`state` int(5) DEFAULT '-1',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1


CREATE TABLE stats (
	id INT AUTO_INCREMENT, 
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	`0` INT DEFAULT -1,
	`41` INT DEFAULT -1,
	`42` INT DEFAULT -1,
	`43` INT DEFAULT -1,
	`44` INT DEFAULT -1,
	`45` INT DEFAULT -1,
	`46` INT DEFAULT -1,
	`47` INT DEFAULT -1,
	`48` INT DEFAULT -1,
	`61` INT DEFAULT -1,
	`62` INT DEFAULT -1,
	`63` INT DEFAULT -1,
	`64` INT DEFAULT -1,
	`65` INT DEFAULT -1,
	`66` INT DEFAULT -1,
	`67` INT DEFAULT -1,
	`68` INT DEFAULT -1,
	PRIMARY KEY (id)
);
