'use strict';

export const RESPONSE_CODE_OK: number = 0;
export const RESPONSE_CODE_READY: number = 1;
export const RESPONSE_CODE_CHECK_TOKEN: number = 2;
export const RESPONSE_CODE_TOKEN_CHECKED: number = 3;

export const CALENDAR_STATUS_GOT_ALL: number = 4;
export const CALENDAR_STATUS_GOT_ONE: number = 5;
export const CALENDAR_STATUS_GOT_EVENTS: number = 6;

export const CALENDAR_STATUS: any = {
	GOT_ALL: CALENDAR_STATUS_GOT_ALL,
	GOT_ONE: CALENDAR_STATUS_GOT_ONE,
	GOT_EVENTS: CALENDAR_STATUS_GOT_EVENTS
};

export const RESPONSE_CODES: any = { 
	OK: RESPONSE_CODE_OK,
	READY: RESPONSE_CODE_READY,
	CHECK_TOKEN: RESPONSE_CODE_CHECK_TOKEN,
	TOKEN_CHECKED: RESPONSE_CODE_TOKEN_CHECKED
};